import 'package:olivia/features/chat/domain/entities/message.dart';

class MessageModel extends MessageEntity {
  const MessageModel({
    required super.id,
    required super.chatRoomId,
    required super.senderId,
    required super.content,
    required super.sentAt,
    super.isRead,
  });

  factory MessageModel.fromJson(Map<String, dynamic> json) {
    return MessageModel(
      id: json['id'] as String,
      chatRoomId: json['chat_room_id'] as String,
      senderId: json['sender_id'] as String,
      content: json['content'] as String,
      sentAt: DateTime.parse(json['sent_at'] as String),
      isRead: (json['is_read'] as bool?) ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      // 'id' biasanya auto-generated by DB
      'chat_room_id': chatRoomId,
      'sender_id': senderId,
      'content': content,
      // 'sent_at' auto-generated by DB
      // 'is_read' default false
    };
  }
}
